import type { ColouringPage } from '../types';
import type { El } from '@/drawing/kit/types';
import { sky } from './common';

/** A big curve of Earth along the bottom of the page. */
const earthBelow = (y = 1060, r = 720): El => ({ k: 'earth', x: 0, y, r });

export const ISRO_PAGES: ColouringPage[] = [
  {
    id: 'ch3-landing', title: 'Vikram lands on the Moon', cat: 'isro', level: 2,
    about: 'On 23 August 2023 Chandrayaan-3’s Vikram lander touched down gently near the Moon’s south pole.',
    facts: ['India now celebrates 23 August as National Space Day.', 'The landing spot is called Shiv Shakti point.'],
    mission: 'chandrayaan-3', model: { id: 'vikram' }, body: 'moon', tags: ['chandrayaan', 'vikram', 'moon'],
    art: [sky([[-380, -420, 36], [-220, -300, 22], [-420, -180, 26], [120, -460, 20], [420, -120, 24]]), { k: 'earth', x: 320, y: -330, r: 100 }, { k: 'ground', y: 390, style: 'moon', seed: 4 }, { k: 'lander', x: 0, y: 170, s: 1.2, parts: true }],
  },
  {
    id: 'pragyan-rover', title: 'Pragyan rolls out', cat: 'isro', level: 2,
    about: 'Pragyan means wisdom. This six-wheeled rover rolled down a ramp and explored the Moon’s soil.',
    facts: ['Pragyan’s wheels left prints of the ISRO logo and India’s national emblem in the Moon dust.', 'It found sulphur in the soil near the south pole.'],
    mission: 'chandrayaan-3', model: { id: 'vikram' }, body: 'moon', tags: ['pragyan', 'rover', 'moon'],
    art: [
      sky([[-400, -440, 34], [-160, -470, 22], [140, -420, 26], [420, -300, 22]]),
      { k: 'earth', x: 330, y: -380, r: 80 },
      { k: 'ground', y: 300, style: 'moon', seed: 9 },
      { k: 'lander', x: -290, y: 40, s: 0.75, ramp: true },
      { k: 'svg', d: 'M-120 420 h40 M-40 420 h40 M40 420 h40 M-120 450 h40 M-40 450 h40 M40 450 h40', x: 0, y: 0 },
      { k: 'rover', x: 180, y: 290, s: 1.5, parts: true },
    ],
  },
  {
    id: 'vikram-pragyan', title: 'Vikram and Pragyan at Shiv Shakti point', cat: 'isro', level: 3,
    about: 'The lander and the rover worked together for about two weeks of Moon daylight.',
    facts: ['A day on the Moon lasts about 14 Earth days.', 'Vikram even did a little hop, lifting off and landing again!'],
    mission: 'chandrayaan-3', model: { id: 'vikram' }, body: 'moon', tags: ['vikram', 'pragyan', 'moon'],
    art: [
      sky([[-400, -440, 30], [-230, -330, 20], [60, -470, 22], [420, -150, 24]]),
      { k: 'earth', x: 300, y: -370, r: 90 },
      { k: 'ground', y: 380, style: 'moon', seed: 12 },
      { k: 'lander', x: -110, y: 150, s: 1.05, parts: true, ramp: true },
      { k: 'rover', x: 330, y: 360, s: 0.9, parts: true },
    ],
  },
  {
    id: 'chandrayaan-1', title: 'Chandrayaan-1 circles the Moon', cat: 'isro', level: 2,
    about: 'India’s first Moon mission, in 2008, orbited the Moon and helped find signs of water there.',
    facts: ['Chandra means Moon and yaan means vehicle.', 'It dropped a small Moon Impact Probe that crashed on purpose to study the Moon.'],
    mission: 'chandrayaan-1', body: 'moon', tags: ['chandrayaan', 'moon', 'orbit'],
    art: [
      sky([[380, 300, 30], [420, 60, 22], [-420, -420, 30], [-160, -460, 22], [200, 440, 24]]),
      { k: 'orbit', x: -150, y: 170, rx: 460, ry: 160, rot: -0.35 },
      { k: 'moon', x: -150, y: 170, r: 300, craters: 7, seed: 21 },
      { k: 'satellite', v: 'ch2orbiter', x: 220, y: -270, s: 0.9 },
    ],
  },
  {
    id: 'chandrayaan-2', title: 'Chandrayaan-2 orbiter', cat: 'isro', level: 2,
    about: 'Launched in 2019, the Chandrayaan-2 orbiter is still circling the Moon and taking sharp pictures.',
    facts: ['Its camera can spot things on the Moon as small as a car.', 'Its pictures help plan where future landers can go.'],
    body: 'moon', tags: ['chandrayaan', 'moon', 'orbit'],
    art: [
      sky([[-420, -420, 34], [-220, -470, 22], [420, 260, 26], [-430, 40, 22]]),
      { k: 'moon', x: 180, y: 250, r: 330, craters: 8, seed: 5 },
      { k: 'satellite', v: 'ch2orbiter', x: -150, y: -210, s: 1.05, rot: 0.15 },
    ],
  },
  {
    id: 'aditya-l1', title: 'Aditya-L1 watches the Sun', cat: 'isro', level: 2,
    about: 'Aditya-L1 sits 1.5 million kilometres from Earth at a balancing spot called L1, looking at the Sun all day.',
    facts: ['Aditya is a Sanskrit name for the Sun.', 'It studies solar storms that can affect satellites and power lines.'],
    mission: 'aditya-l1', body: 'sun', tags: ['aditya', 'sun'],
    art: [
      sky([[330, -430, 30], [440, -200, 22], [200, 420, 26], [-420, 430, 22]]),
      { k: 'sun', x: -300, y: -150, r: 200, rays: 14, corona: true },
      { k: 'satellite', v: 'aditya', x: 230, y: 180, s: 0.9, rot: 0.5, flip: true },
      { k: 'earth', x: 440, y: 440, r: 60 },
    ],
  },
  {
    id: 'mangalyaan-mars', title: 'Mangalyaan at Mars', cat: 'isro', level: 2,
    about: 'In 2014 Mangalyaan reached Mars on India’s very first try, after about 300 days in space.',
    facts: ['India was the first country to reach Mars orbit on its first attempt.', 'It sent back pictures of Mars for about eight years.'],
    mission: 'mangalyaan', model: { id: 'mangalyaan' }, body: 'mars', tags: ['mangalyaan', 'mars', 'mom'],
    art: [
      sky([[380, 330, 30], [430, 80, 22], [-430, -430, 26], [-200, -460, 20], [120, 450, 22]]),
      { k: 'orbit', x: -170, y: 190, rx: 470, ry: 170, rot: -0.4 },
      { k: 'planet', x: -170, y: 190, r: 300, craters: 6, seed: 8 },
      { k: 'orbiter', x: 160, y: -250, s: 1, parts: true, rot: 0.1 },
    ],
  },
  {
    id: 'gaganyaan-orbit', title: 'Gaganyaan crew module in orbit', cat: 'isro', level: 2,
    about: 'Gaganyaan is India’s human spaceflight programme. Its crew module will carry astronauts around Earth.',
    facts: ['The service module under the capsule gives it power and pushes it around.', 'The crew module comes back home on its own, protected by a heat shield.'],
    mission: 'gaganyaan', tags: ['gaganyaan', 'astronaut'],
    art: [sky([[-400, -430, 34], [-420, -150, 24], [400, -440, 30], [420, -170, 22], [-250, -470, 18]]), earthBelow(), { k: 'capsule', x: 0, y: -80, s: 1.2, service: true, rot: -0.2 }],
  },
  {
    id: 'gaganyaan-splash', title: 'Gaganyaan splashdown', cat: 'isro', level: 2,
    about: 'Coming home, the crew module opens big parachutes and lands gently in the sea, where a ship picks it up.',
    facts: ['The heat shield glows as the capsule rushes through the air.', 'The parachutes slow the capsule down to a gentle splash.'],
    mission: 'gaganyaan', tags: ['gaganyaan', 'parachute', 'sea'],
    art: [
      { k: 'cloud', x: -380, y: -380, w: 220, h: 100 },
      { k: 'cloud', x: 400, y: -120, w: 180, h: 90 },
      { k: 'ground', y: 360, style: 'sea' },
      { k: 'boat', x: 330, y: 330, s: 0.6 },
      { k: 'parachutes', x: 0, y: 40, s: 0.95 },
      { k: 'capsule', x: 0, y: 140, s: 0.9 },
    ],
  },
  {
    id: 'spadex', title: 'SpaDeX: satellites shake hands', cat: 'isro', level: 2,
    about: 'In January 2025 two ISRO satellites, Chaser and Target, found each other in orbit and docked together.',
    facts: ['India became the fourth country to dock spacecraft in space.', 'Docking is a skill needed to build a space station.'],
    mission: 'spadex', tags: ['spadex', 'docking'],
    art: [
      sky([[-400, -430, 32], [-150, -460, 22], [150, -440, 26], [420, -400, 22], [-440, -120, 20], [440, -110, 24]]),
      earthBelow(1100, 760),
      { k: 'satellite', v: 'spadex', x: -215, y: -40, s: 1 },
      { k: 'satellite', v: 'spadex-target', x: 215, y: -40, s: 1 },
      { k: 'tag', t: 'Chaser', x: -215, y: 110, size: 30 },
      { k: 'tag', t: 'Target', x: 215, y: 110, size: 30 },
    ],
  },
  {
    id: 'aryabhata', title: 'Aryabhata, India’s first satellite', cat: 'isro', level: 2,
    about: 'Built by ISRO and launched in 1975, Aryabhata was named after a great Indian mathematician and astronomer.',
    facts: ['It had 26 sides covered in solar cells.', 'It appeared on the Indian two-rupee note.'],
    mission: 'aryabhata', tags: ['aryabhata', 'history', 'satellite'],
    art: [sky([[-400, -430, 34], [-410, -150, 24], [400, -440, 30], [420, -140, 24], [0, -470, 20]]), earthBelow(), { k: 'satellite', v: 'aryabhata', x: 0, y: -120, s: 1.6 }],
  },
  {
    id: 'astrosat', title: 'AstroSat, India’s space telescope', cat: 'isro', level: 2,
    about: 'AstroSat looks at stars and galaxies in many kinds of light at the same time.',
    facts: ['It was launched in 2015.', 'It found faraway galaxies giving out ultraviolet light.'],
    tags: ['astrosat', 'telescope', 'galaxy'],
    art: [
      sky([[-420, 160, 26], [-300, 420, 22], [420, 420, 26], [200, 460, 20]]),
      { k: 'galaxy', x: 260, y: -320, r: 190, arms: 3, tilt: -0.3 },
      { k: 'satellite', v: 'astrosat', x: -80, y: 170, s: 1.15, rot: 0.35 },
    ],
  },
  {
    id: 'navic', title: 'NavIC, India’s own GPS', cat: 'isro', level: 2,
    about: 'NavIC satellites send signals that help phones, ships and cars in India know exactly where they are.',
    facts: ['NavIC stands for Navigation with Indian Constellation.', 'Each satellite carries very accurate atomic clocks.'],
    tags: ['navic', 'navigation', 'satellite'],
    art: [
      sky([[-420, -450, 26], [0, -470, 22], [420, -450, 26]]),
      earthBelow(1080, 700),
      { k: 'beam', x: -330, y: -150, dir: 1.2, n: 3, r: 360 },
      { k: 'beam', x: 0, y: -260, dir: Math.PI / 2, n: 3, r: 420 },
      { k: 'beam', x: 330, y: -150, dir: 1.94, n: 3, r: 360 },
      { k: 'satellite', v: 'navic', x: -330, y: -230, s: 0.55 },
      { k: 'satellite', v: 'navic', x: 0, y: -340, s: 0.55 },
      { k: 'satellite', v: 'navic', x: 330, y: -230, s: 0.55 },
    ],
  },
  {
    id: 'insat-weather', title: 'INSAT watches the weather', cat: 'isro', level: 2,
    about: 'INSAT satellites watch clouds and storms over India so forecasters can warn people in time.',
    facts: ['They stay above the same spot on Earth all the time.', 'Their pictures help track cyclones over the sea.'],
    tags: ['insat', 'weather', 'satellite'],
    art: [
      sky([[-420, -440, 30], [-160, -470, 22], [420, -120, 22]]),
      { k: 'earth', x: -60, y: 780, r: 620 },
      { k: 'cloud', x: -220, y: 240, w: 220, h: 90 },
      { k: 'cloud', x: 150, y: 290, w: 200, h: 80 },
      { k: 'satellite', v: 'insat', x: 40, y: -260, s: 0.95 },
    ],
  },
  {
    id: 'cartosat', title: 'Cartosat makes maps', cat: 'isro', level: 2,
    about: 'Cartosat satellites take very sharp pictures of the ground to help make maps of cities, farms and forests.',
    facts: ['Carto means map.', 'Maps from space help plan roads and find where to plant trees.'],
    tags: ['cartosat', 'maps', 'satellite'],
    art: [
      sky([[-420, -440, 30], [420, -440, 28], [-420, -200, 22], [430, -210, 22]]),
      { k: 'beam', x: 0, y: -150, dir: Math.PI / 2, n: 4, r: 520 },
      { k: 'ground', y: 360, style: 'hills' },
      { k: 'svg', d: 'M-520 460 L-300 420 L-80 470 L140 410 L360 460 L540 430 M-200 420 L-160 560 M200 415 L240 560', x: 0, y: 0 },
      { k: 'satellite', v: 'cartosat', x: 0, y: -260, s: 0.85 },
    ],
  },
  {
    id: 'nisar', title: 'NISAR and its giant umbrella', cat: 'isro', level: 3,
    about: 'NISAR was built by ISRO and NASA together. Its huge golden antenna opens like an umbrella in space.',
    facts: ['Its antenna is about 12 metres across, as wide as a bus is long.', 'It can spot tiny movements of the ground, ice and forests.'],
    tags: ['nisar', 'radar', 'satellite'],
    art: [sky([[-420, -440, 30], [-420, 60, 24], [400, 320, 26], [-120, 440, 22]]), earthBelow(1180, 700), { k: 'satellite', v: 'nisar', x: -210, y: 60, s: 0.95 }],
  },
  {
    id: 'xposat', title: 'XPoSat studies X-rays', cat: 'isro', level: 2,
    about: 'XPoSat studies X-rays coming from black holes and dead stars far away in space.',
    facts: ['It was launched on 1 January 2024.', 'X-rays are a kind of light our eyes cannot see.'],
    tags: ['xposat', 'black hole', 'x-ray'],
    art: [sky([[-420, -440, 26], [-420, 380, 24], [420, 420, 26], [140, 460, 20]]), { k: 'blackhole', x: 250, y: -300, r: 70 }, { k: 'satellite', v: 'xposat', x: -110, y: 170, s: 1.1, rot: 0.4 }],
  },
  {
    id: 'bharatiya-station', title: 'Bharatiya Antariksh Station', cat: 'isro', level: 3,
    about: 'India plans to build its own space station, where gaganyatris can live and do science in orbit.',
    facts: ['It will be built piece by piece, one module at a time.', 'Docking, like SpaDeX showed, is how the pieces join.'],
    tags: ['station', 'future', 'gaganyaan'],
    art: [sky([[-420, -450, 30], [0, -470, 22], [420, -450, 30], [-440, 330, 22], [440, 300, 24]]), earthBelow(1180, 700), { k: 'station', x: 0, y: -60, s: 0.95 }],
  },
];
