import type { ColouringPage } from '../types';
import { ROCKET_SKY, padScene, sky, smoke, sriharikota } from './common';

export const ROCKET_PAGES: ColouringPage[] = [
  {
    id: 'pslv-xl-pad', title: 'PSLV-XL on the launch pad', cat: 'rockets', level: 2,
    about: 'PSLV is India’s workhorse rocket. The XL version wears six strap-on boosters.',
    facts: ['PSLV has four stages that fire one after another.', 'In 2017 one PSLV carried 104 satellites into space in a single launch.'],
    mission: 'pslv', model: { id: 'pslv', options: { boosters: 6 } }, tags: ['pslv', 'sriharikota'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(), { k: 'rocket', v: 'pslv', x: 0, y: 348, s: 0.95, parts: true }],
  },
  {
    id: 'pslv-liftoff', title: 'PSLV lifts off!', cat: 'rockets', level: 2,
    about: 'Three, two, one… liftoff! The first stage and boosters give PSLV its mighty first push.',
    facts: ['Hot gas rushes down out of the nozzle, so the rocket goes up.', 'The boosters drop away when their fuel runs out.'],
    mission: 'pslv', model: { id: 'pslv', options: { boosters: 6 } }, tags: ['pslv', 'launch'],
    art: [sky(ROCKET_SKY), { k: 'rocket', v: 'pslv', x: 0, y: 170, s: 0.76, flame: 'big', parts: true }, ...smoke(430)],
  },
  {
    id: 'pslv-ca', title: 'PSLV-CA, the Core Alone rocket', cat: 'rockets', level: 1,
    about: 'PSLV can fly with no boosters at all. That version is called Core Alone.',
    facts: ['PSLV comes in outfits with 0, 2, 4 or 6 boosters.', 'Lighter satellites need less push, so fewer boosters.'],
    mission: 'pslv', model: { id: 'pslv', options: { boosters: 0 } }, tags: ['pslv'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(0, 200), { k: 'rocket', v: 'pslv-ca', x: 0, y: 348, s: 0.95, parts: true }],
  },
  {
    id: 'gslv', title: 'GSLV and its four strap-ons', cat: 'rockets', level: 2,
    about: 'GSLV has four liquid-fuel strap-on boosters and a super-cold cryogenic top stage.',
    facts: ['GSLV lifts heavy satellites high above Earth.', 'In 2025 a GSLV launched NISAR, a satellite built by India and the USA together.'],
    tags: ['gslv', 'cryogenic'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(0, 230), { k: 'rocket', v: 'gslv', x: 0, y: 350, s: 0.97 }],
  },
  {
    id: 'lvm3-pad', title: 'LVM3, India’s most powerful rocket', cat: 'rockets', level: 2,
    about: 'LVM3 has two giant solid boosters and a cryogenic upper stage. It sent Chandrayaan-3 to the Moon.',
    facts: ['Its S200 boosters are among the biggest solid rocket boosters in the world.', 'LVM3 used to be called GSLV Mk III.'],
    mission: 'lvm3', model: { id: 'lvm3' }, tags: ['lvm3', 'chandrayaan'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(0, 260), { k: 'rocket', v: 'lvm3', x: 0, y: 350, s: 1.1, parts: true }],
  },
  {
    id: 'lvm3-liftoff', title: 'LVM3 blasts off', cat: 'rockets', level: 2,
    about: 'Both S200 boosters roar together to lift LVM3 off the pad.',
    facts: ['The boosters burn for about two minutes, then fall away.', 'The core stage has two Vikas engines side by side.'],
    mission: 'lvm3', model: { id: 'lvm3' }, tags: ['lvm3', 'launch'],
    art: [sky(ROCKET_SKY), { k: 'rocket', v: 'lvm3', x: 0, y: 190, s: 0.95, flame: 'big', parts: true }, ...smoke(440)],
  },
  {
    id: 'lvm3-crew', title: 'Human-rated LVM3 for Gaganyaan', cat: 'rockets', level: 3,
    about: 'For astronauts, LVM3 carries the Gaganyaan crew module with an escape tower on top for safety.',
    facts: ['If anything goes wrong, the escape tower pulls the crew module away from the rocket.', 'Gaganyaan astronauts are called gaganyatris.'],
    mission: 'gaganyaan', model: { id: 'lvm3', options: { crew: true } }, tags: ['lvm3', 'gaganyaan', 'astronaut'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(0, 260), { k: 'rocket', v: 'lvm3-crew', x: 0, y: 350, s: 1.1, parts: true }],
  },
  {
    id: 'sslv', title: 'SSLV, the Small Satellite Launch Vehicle', cat: 'rockets', level: 1,
    about: 'SSLV is a small, quick rocket for small satellites. It can be got ready in just a few days.',
    facts: ['SSLV has three solid-fuel stages and a small liquid-fuel stage on top.', 'Its first successful flight carried a satellite called EOS-07.'],
    tags: ['sslv'],
    art: [sky([[-360, -400, 44], [-220, -250, 28], [380, -420, 36], [300, -220, 26], [-400, -60, 22], [420, 0, 24]]), ...sriharikota(), ...padScene(0, 180), { k: 'rocket', v: 'sslv', x: 0, y: 354, s: 1.2 }],
  },
  {
    id: 'slv3', title: 'SLV-3, the very first launcher', cat: 'rockets', level: 2,
    about: 'In 1980 SLV-3 put the Rohini satellite into orbit. India became a country that could launch its own satellites.',
    facts: ['Dr A P J Abdul Kalam led the SLV-3 project.', 'SLV-3 had four stages, all using solid fuel.'],
    tags: ['history', 'kalam'],
    art: [sky([[-360, -400, 40], [-230, -240, 26], [360, -420, 34], [280, -250, 22], [-400, -40, 22], [400, 20, 26]]), ...sriharikota(), ...padScene(0, 170), { k: 'rocket', v: 'slv3', x: 0, y: 358, s: 1.25 }, { k: 'satellite', v: 'aryabhata', x: -300, y: -300, s: 0.5 }],
  },
  {
    id: 'aslv', title: 'ASLV with two strap-ons', cat: 'rockets', level: 2,
    about: 'The Augmented Satellite Launch Vehicle added two boosters to the SLV-3 design to lift more.',
    facts: ['ASLV flew in the late 1980s and early 1990s.', 'Lessons from ASLV helped ISRO build PSLV.'],
    tags: ['history'],
    art: [sky(ROCKET_SKY), ...sriharikota(), ...padScene(0, 190), { k: 'rocket', v: 'aslv', x: 0, y: 358, s: 1.25 }],
  },
  {
    id: 'rohini-sounding', title: 'Rohini sounding rocket', cat: 'rockets', level: 1,
    about: 'Sounding rockets fly straight up for a few minutes to study the air high above us, then fall back.',
    facts: ['ISRO still launches small Rohini rockets to study the sky.', 'They are launched from Thumba, near Thiruvananthapuram.'],
    tags: ['thumba', 'sounding'],
    art: [sky([[-330, -380, 50], [340, -400, 44], [-220, -150, 30], [260, -120, 34], [-380, 120, 26], [380, 160, 30]]), { k: 'ground', y: 430, style: 'hills' }, { k: 'palm', x: -400, y: 240, s: 0.85 }, { k: 'palm', x: 380, y: 250, s: 0.8, flip: true }, { k: 'rocket', v: 'rohini', x: 0, y: 380, s: 1.4, flame: true }],
  },
  {
    id: 'thumba-bicycle', title: 'Thumba 1963: rocket parts on a bicycle', cat: 'rockets', level: 2,
    about: 'India’s very first rocket launch was in 1963 at Thumba. Scientists carried rocket parts on bicycles!',
    facts: ['That first rocket was a Nike-Apache sounding rocket.', 'Dr Vikram Sarabhai started India’s space programme from Thumba.'],
    tags: ['history', 'thumba', 'sarabhai'],
    art: [
      sky([[-380, -420, 40], [-200, -320, 26], [380, -450, 32], [220, -380, 22]]),
      { k: 'ground', y: 360, style: 'grass' },
      { k: 'palm', x: -420, y: 160, s: 0.85 },
      { k: 'rocket', v: 'nike-apache', x: 340, y: 330, s: 1.05 },
      { k: 'bicycle', x: -60, y: 230, s: 1.05 },
    ],
  },
  {
    id: 'rlv-pushpak', title: 'RLV Pushpak, the reusable spaceplane', cat: 'rockets', level: 2,
    about: 'RLV is a winged test vehicle. ISRO is learning to land a spacecraft on a runway, like an aeroplane, so it can fly again.',
    facts: ['Reusing a rocket makes going to space much cheaper.', 'Pushpak made landing tests in 2023 and 2024.'],
    tags: ['rlv', 'reusable'],
    art: [
      sky([[-380, -420, 40], [380, -440, 34], [-420, -180, 26], [430, -160, 24]]),
      { k: 'cloud', x: -330, y: -30, w: 220, h: 100 },
      { k: 'cloud', x: 350, y: 60, w: 200, h: 90 },
      { k: 'ground', y: 420, style: 'flat' },
      { k: 'svg', d: 'M-520 470 L520 470 M-420 445 L-340 445 M-220 445 L-140 445 M-20 445 L60 445 M180 445 L260 445 M380 445 L460 445', x: 0, y: 0 },
      { k: 'shuttle', x: 0, y: 40, s: 1.15, rot: 1.3 },
    ],
  },
  {
    id: 'rocket-family', title: 'India’s rocket family', cat: 'rockets', level: 3,
    about: 'From small to big: SSLV, PSLV, GSLV and LVM3. Each one is built for a different job.',
    facts: ['Small rockets launch small satellites quickly.', 'Big rockets carry heavy satellites, Moon missions and one day astronauts.'],
    tags: ['sslv', 'pslv', 'gslv', 'lvm3'],
    art: [
      sky([[-400, -440, 30], [-230, -470, 20], [80, -470, 22], [400, -470, 24]]),
      { k: 'ground', y: 360, style: 'flat' },
      { k: 'rocket', v: 'sslv', x: -360, y: 340, s: 0.62 },
      { k: 'rocket', v: 'pslv', x: -150, y: 340, s: 0.62 },
      { k: 'rocket', v: 'gslv', x: 70, y: 340, s: 0.62 },
      { k: 'rocket', v: 'lvm3', x: 310, y: 340, s: 0.7 },
      { k: 'tag', t: 'SSLV', x: -360, y: 420, size: 30 },
      { k: 'tag', t: 'PSLV', x: -150, y: 420, size: 30 },
      { k: 'tag', t: 'GSLV', x: 70, y: 420, size: 30 },
      { k: 'tag', t: 'LVM3', x: 310, y: 420, size: 30 },
    ],
  },
  {
    id: 'future-rocket', title: 'A rocket of the future', cat: 'rockets', level: 1,
    about: 'ISRO is designing a new, bigger rocket that can be used again and again. What colours would you give it?',
    facts: ['Future rockets may land back on Earth after a launch.', 'Reusable rockets could help build India’s own space station.'],
    tags: ['future', 'reusable'],
    art: [sky([[-380, -420, 44], [-240, -260, 28], [380, -430, 38], [300, -250, 26], [-420, -40, 24], [430, 20, 26]]), { k: 'ground', y: 440, style: 'hills' }, { k: 'rocket', v: 'ngl', x: 0, y: 360, s: 1.05 }],
  },
];
